### ISSUE TITLE
新手求教

### ISSUE THREAD

**Issue by 94club** [cuo9958/react-native-tabs-top#1]
// <ScrollView ref={e => this.scroll = e}</Scrollview>
// <TabBar ref={e => this.tabs = e}</TabBar>
请问一下 这种赋值该怎么理解了，新手求教， 期待您的回复
------
已经找到资料了  是ref的高级用法

**Comment by cuo9958** [comment]
就是在class内部复制一个变量，变量值是这个组件初始化之后的对象
