### ISSUE TITLE
导入组件报错

### ISSUE THREAD

**Issue by imaxing** [cuo9958/react-native-tabs-top#3]
> 导入

![image](https://user-images.githubusercontent.com/26427785/63227177-78025a80-c216-11e9-99af-d41d3515741d.png)

> 报错

![image](https://user-images.githubusercontent.com/26427785/63227159-53a67e00-c216-11e9-9754-f845713f28cf.png)

**Comment by cuo9958** [comment]
报错显示loader处理不了这个文件，看下是不是配置的时候没有把这个文件加入进去。

开发的时候这个库是在0.53上验证的。
